
-- Tabla CATEGORY
CREATE TABLE IF NOT EXISTS CATEGORY (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    Status BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla PROMOTION
CREATE TABLE IF NOT EXISTS PROMOTION (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    amount DECIMAL(10, 2),
    type VARCHAR(50),
    startDate DATE,
    endDate DATE,
    Status BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla PRODUCT
CREATE TABLE IF NOT EXISTS PRODUCT (
    ID SERIAL PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    expirationDate DATE,
    price DECIMAL(10, 2) NOT NULL,
    ID_category INT,
    ID_promotion INT,
    Status BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (ID_category) REFERENCES CATEGORY(ID),
    FOREIGN KEY (ID_promotion) REFERENCES PROMOTION(ID)
);

-- ... (continúa el cambio a SERIAL PRIMARY KEY en el resto de las tablas)

-- Tabla SUPPLIER
CREATE TABLE IF NOT EXISTS SUPPLIER (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(255),
    Status BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla CAFE
CREATE TABLE IF NOT EXISTS CAFE (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    company VARCHAR(255),
    Status BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla INVENTORY
CREATE TABLE IF NOT EXISTS INVENTORY (
    ID SERIAL PRIMARY KEY,
    ID_cafe INT,
    ID_product INT,
    quantity INT NOT NULL,
    ID_supplier INT,
    Status BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (ID_cafe) REFERENCES CAFE(ID),
    FOREIGN KEY (ID_product) REFERENCES PRODUCT(ID),
    FOREIGN KEY (ID_supplier) REFERENCES SUPPLIER(ID)
);

-- Tabla USERS
CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(20),
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    Rrole VARCHAR(50) NOT NULL,
    Status BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tabla SHOPPING
CREATE TABLE IF NOT EXISTS SHOPPING (
    ID SERIAL PRIMARY KEY,
    ID_user INT,
    date TIMESTAMP WITHOUT TIME ZONE NOT NULL, -- Uso de TIMESTAMP para la fecha y hora
    total DECIMAL(10, 2) NOT NULL,
    Discount DECIMAL(10, 2),
    Promotion VARCHAR(255),
    Status BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (ID_user) REFERENCES USERS(ID)
);

-- Tabla SHOPPING_DETAIL
CREATE TABLE IF NOT EXISTS SHOPPING_DETAIL (
    ID SERIAL PRIMARY KEY,
    ID_product INT,
    quantity INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    ID_shopping INT,
    Status BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (ID_product) REFERENCES PRODUCT(ID),
    FOREIGN KEY (ID_shopping) REFERENCES SHOPPING(ID)
);

-- Tabla PURCHASE_HISTORY
CREATE TABLE IF NOT EXISTS PURCHASE_HISTORY (
    ID SERIAL PRIMARY KEY,
    IdUser INT,
    IdShopping INT,
    Id_payment VARCHAR(255),
    Status BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (IdUser) REFERENCES USERS(ID),
    FOREIGN KEY (IdShopping) REFERENCES SHOPPING(ID)
);